<a href="https://colab.research.google.com/github/sushma566/AIML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A1=np.array([[[1,2,3],[2,4,5]],[[1,2,3],[1,3,4]]])
print(A1)

[[[1 2 3]
  [2 4 5]]

 [[1 2 3]
  [1 3 4]]]


In [ ]:
A1.size

12

In [ ]:
A1.shape

(2, 2, 3)

In [ ]:
a2=np.array([[[[1,2,3],[2,4,5]],[[1,2,3],[1,3,4]]],[[[1,2,3],[2,4,5]],[[1,2,3],[1,3,4]]]])
print(a2)

[[[[1 2 3]
   [2 4 5]]

  [[1 2 3]
   [1 3 4]]]


 [[[1 2 3]
   [2 4 5]]

  [[1 2 3]
   [1 3 4]]]]


In [ ]:
a2.shape

(2, 2, 2, 3)

In [ ]:
a2.size

24

In [ ]:
import numpy as np

In [ ]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
import numpy as np
z1=np.zeros((3,4),dtype=int)
z1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z2=np.zeros((4,3),dtype=int)
z2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
z2=np.zeros((4,3,3),dtype=int)
z2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
z2.size

36

In [ ]:

a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2=np.ones((3,4),dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a2=np.ones((2,3,4),dtype=int)
a2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
a2=np.ones((1,2,3,4),dtype=int)
a2

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]])

In [ ]:
A1=np.full(5,36)
A1

array([36, 36, 36, 36, 36])

In [ ]:
A1=np.full([5,36],7)
A1

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [ ]:

a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
add=np.add(a,b)
print(add)
sub=np.subtract(a,b)
print(sub)
mul=np.multiply(a,b)
print(mul)
div=np.divide(a,b)
print(div)

[ 4  6  8 10]
[-2 -2 -2 -2]
[ 3  8 15 24]
[0.33333333 0.5        0.6        0.66666667]
